src/Entity/Wine/Color.php
<?php

namespace App\Entity\Wine;

use App\Entity\Traits\DoctrineEventsTrait;
use App\Entity\Traits\WineTrait;
use App\Entity\User\User;
use App\Repository\Wine\ColorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Table(name="wine_color")
 * @ORM\Entity(repositoryClass=ColorRepository::class)
 */
class Color extends AbstractWine
{
    use DoctrineEventsTrait;
    use WineTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $CssCode;

    /**
     * @var Wine[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Wine\Wine",  mappedBy="color", fetch="EXTRA_LAZY", cascade={"persist"})
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $wines;

    public function __construct()
    {
        $this->popularity = 0;
        $this->wines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString(): string
    {
        return (string)$this->id;
    }

    public function isCreator(User $user): bool
    {
        if ($this->createdBy->getId() == $user->getId()) {
            return true;
        }

        return false;
    }

    public function addPopularity(): void
    {
        $this->popularity++;
    }

    public function removePopularity(): void
    {
        $this->popularity--;
    }

    public function getCssCode(): ?string
    {
        return $this->CssCode;
    }

    public function setCssCode(string $CssCode): self
    {
        $this->CssCode = $CssCode;

        return $this;
    }

    /**
     * @return Collection|Wine[]
     */
    public function getWines(): Collection
    {
        return $this->wines;
    }

    public function hasUploadedFile(): bool
    {
        if ($this->file instanceof UploadedFile) {
            return true;
        }
        return false;
    }

    public function addWine(Wine $wine): self
    {
        if (!$this->wines->contains($wine)) {
            $this->wines[] = $wine;
            $wine->setColor($this);
        }

        return $this;
    }

    public function removeWine(Wine $wine): self
    {
        if ($this->wines->contains($wine)) {
            $this->wines->removeElement($wine);
            // set the owning side to null (unless already changed)
            if ($wine->getColor() === $this) {
                $wine->setColor(null);
            }
        }

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\User\User;
use App\Util\WineData;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /** @var EntityManagerInterface */
    private $entityManager;

    /** @var WineData */
    private $wineData;

    public function __construct(EntityManagerInterface $entityManager, WineData $wineData)
    {
        $this->entityManager = $entityManager;
        $this->wineData = $wineData;
    }

    /**
     * @Route("/", name="homepage")
     * @IsGranted("ROLE_USER", statusCode="403")
     */
    public function homepageAction(EntityManagerInterface $entityManager)
    {
        /** @var User */
        $user = $this->getUser();

        return $this->render('default/homepage.html.twig', [
            'getWineColorsInBox' => $this->wineData->getWineColorsInBox(),
            'getWineConsumptionYears' => $this->wineData->getWineConsumptionYears(),
            'getWineBottlesInBoxCount' => $this->wineData->getWineBottlesInBoxCount(),
            'getWineBoxPercent' => $this->wineData->getWineBoxPercent(),
            'wineConsumptionInLiter' => $user->getBox()->getLiter(),
            'getWineBoxLeftPlaces' => $this->wineData->getWineBoxLeftPlaces(),
            'getWineBottleApogee' => $this->wineData->getWineBottleApogee(),
            'getWineBottleAlert' => $this->wineData->getWineBottleAlert(),
        ]);
    }
}

templates/default/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block body %}
    <div class="row">
        {% for wineColor in getWineColorsInBox %}
            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 items">
                <div class="item {{ wineColor.entity.slug }}" style="background-color: {{ wineColor.entity.cssCode }}">
                    <span class="name {{ wineColor.entity.slug }}">{{ wineColor.entity.name }}</span>
                    <span class="count {{ wineColor.entity.slug }}"><span class="countOnNumber">{{ wineColor.count }}</span></span>
                    <span class="logo {{ wineColor.entity.slug }}"><i class="fas fa-wine-bottle"></i></span>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="ui form" id="chart_consumption_years">
            <div class="field">
                <select id="consumption_years" class="ui search dropdown">
                    {% for value in getWineConsumptionYears %}
                        <option value="{{ value.year }}">{{ value.year }}</option>
                    {% endfor %}
                    <option value="LAST_SIX_MONTH" selected>Les 6 Derniers Mois</option>
                </select>
            </div>
        </div>
        <div class="col-lg-12 chart_consumption" id="chart_consumption"></div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 items">
            <div class="item blanc">
                <span class="name blanc">Bottles In Box</span>
                <span class="count blanc"><span class="countOnNumber">{{ getWineBottlesInBoxCount }}</span></span>
                <span class="logo blanc"><i class="fas fa-wine-bottle"></i></span>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 items">
            <div class="item" style="background-color: {{ getWineBoxPercent.color }}">
                <span class="name">Filling Rate</span>
                <span class="count"><span class="countOnNumber">{{ getWineBoxPercent.percent }}</span>%</span>
                <span class="logo"><i class="fas fa-wine-bottle"></i></span>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 items">
            <div class="item" style="background-color: {{ getWineBoxLeftPlaces.color }}">
                <span class="name">Left Places</span>
                <span class="count"><span class="countOnNumber">{{ getWineBoxLeftPlaces.left_places }}</span></span>
                <span class="logo"><i class="fas fa-wine-bottle"></i></span>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 items">
            <div class="item consumption_liter">
                <span class="name">Total Consumption</span>
                <span class="count"><span class="countOnNumber">{{ wineConsumptionInLiter }}</span>L</span>
                <span class="logo"><i class="fas fa-wine-bottle"></i></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 chart_country" id="chart_country"></div>
    </div>
    <div class="row">
        <div class="col-lg-6 apogee_at items" id="apogee_at">
            <table class="ui celled selectable striped table">
                <thead>
                <tr>
                    <th colspan="3">
                        Apogee Is Soon
                    </th>
                </tr></thead>
                <tbody>
                {% for bottle in getWineBottleApogee %}
                    <tr>
                        <td class="collapsing">
                            <i class="fas fa-wine-bottle" style="color: {{ bottle.css_code }};"></i>&nbsp;&nbsp;&nbsp;<a href="">{{ bottle.name }}</a>
                        </td>
                        <td>{{ bottle.apogee_at|date("d F Y") }}</td>
                        <td class="right aligned collapsing">{{ bottle.location }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-6 apogee_at items" id="alert_at">
            <table class="ui celled selectable striped table">
                <thead>
                <tr>
                    <th colspan="3">
                        Alert Is Soon
                    </th>
                </tr></thead>
                <tbody>
                {% for bottle in getWineBottleAlert %}
                    <tr>
                        <td class="collapsing">
                            <i class="fas fa-wine-bottle" style="color: {{ bottle.css_code }};"></i>&nbsp;&nbsp;&nbsp;<a href="">{{ bottle.name }}</a>
                        </td>
                        <td>{{ bottle.alert_at|date("d F Y") }}</td>
                        <td class="right aligned collapsing">{{ bottle.location }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script type="application/javascript" src="https://code.highcharts.com/maps/highmaps.js"></script>
    <script type="application/javascript" src="https://code.highcharts.com/mapdata/custom/world.js"></script>

    <script>
        $.get({
            url: '{{ path('ajax_wine_box_country') }}',
            type: 'GET',
            async: true,
            success: function (elements) {
                Highcharts.mapChart('chart_country', {
                    chart: {
                        map: 'custom/world',
                        borderWidth: 1,
                        spacingBottom: 45,
                        spacingTop: 25,
                        spacingLeft: 10,
                        spacingRight: 10,
                        borderColor: 'rgb(230, 230, 230)',
                        style: {
                            fontFamily: 'Raleway-Bold',
                        }
                    },
                    colors: [
                        'rgba(19,64,117,0.4)',
                        'rgba(19,64,117,0.5)',
                        'rgba(19,64,117,0.6)',
                        'rgba(19,64,117,0.8)',
                        'rgba(19,64,117,1)'
                    ],
                    title: {
                        text: null
                    },
                    credits: {
                        enabled: false
                    },
                    mapNavigation: {
                        enabled: true
                    },
                    colorAxis: {
                        dataClasses: [{
                            to: 2
                        }, {
                            from: 2,
                            to: 5
                        }, {
                            from: 5,
                            to: 10
                        }, {
                            from: 10,
                            to: 30
                        }, {
                            from: 30
                        }]
                    },
                    legend: {
                        enabled: false
                    },
                    series: [{
                        data: elements,
                        joinBy: ['iso-a3', 'code'],
                        animation: true,
                        name: 'Wine Bottles By Country',
                        states: {
                            hover: {
                                color: '#edafa4'
                            }
                        },
                        shadow: false
                    }]
                });
            }
        })

    </script>
    <script>
        $('#chart_consumption_years .ui.dropdown').dropdown({
            action: 'activate',
            onChange: function (value) {
                $.get({
                    url: '{{ path('ajax_wine_consumption_year') }}',
                    type: 'GET',
                    async: true,
                    data: {'year': value},
                    success: function (elements) {
                        loadCharts(elements)
                    }
                })
            }
        })

        $('.countOnNumber').each(function () {
            $(this).prop('Counter',0).animate({
                Counter: $(this).text()
            }, {
                duration: 3000,
                easing: 'swing',
                step: function (now) {
                    $(this).text(Math.ceil(now));
                }
            });
        });

        function loadCharts(elements) {
            var categories = [], quantity = [], liter = []

            var year = $('#chart_consumption_years .ui.dropdown').dropdown('get value')
            if (year === "LAST_SIX_MONTH") {
                year = "the Last Six Month"
            }

            $.each(elements, function (index, element) {
                categories.push(element.date)
                quantity.push(parseFloat(element.quantity))
                liter.push(parseFloat(element.liter))
            })

            Highcharts.chart('chart_consumption', {
                chart: {
                    type: 'line',
                    borderWidth: 1,
                    spacingBottom: 45,
                    spacingTop: 25,
                    spacingLeft: 10,
                    spacingRight: 10,
                    borderColor: 'rgb(230, 230, 230)',
                    zoomType: 'x',
                    style: {
                        fontFamily: 'Raleway-Bold',
                    }
                },
                legend: {
                    enabled: false
                },
                credits: {
                    enabled: false
                },
                title: {
                    text: 'Wine Consumption for ' + year
                },
                xAxis: {
                    categories: categories
                },
                yAxis: {
                    title: {
                        text: 'Consumption (Quantity & Liter)'
                    }
                },
                tooltip: {
                    crosshairs: true,
                    shared: true,
                    style: {
                        fontSize: 15
                    }
                },
                colors: ['#7cb5ec', '#c0392b'],
                plotOptions: {
                    series: {
                        label: {
                            connectorAllowed: false,
                            style: {
                                fontSize: 40
                            }
                        },
                    },
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                    }
                },
                series: [{
                    name: 'Quantity',
                    data: quantity,
                    marker: {
                        enabled: true,
                        symbol: 'circle',
                        radius: 6,
                    }
                },{
                    name: 'Liter',
                    data: liter,
                    marker: {
                        enabled: true,
                        symbol: 'circle',
                        radius: 6,
                    }
                }]
            });
        }

        $.get({
            url: '{{ path('ajax_wine_consumption_year') }}',
            type: 'GET',
            async: true,
            data: {'year': 'LAST_SIX_MONTH'},
            success: function (elements) {
                loadCharts(elements)
            }
        })
    </script>
{% endblock %}